version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: ${MYSQL_CONTAINER_NAME_DEV}
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DEV}
    ports:
      - ${MYSQL_PORT_DEV}
    stdin_open: true
    tty: true
