version: "3"

services:
  mysql:
    image: mysql:oraclelinux8
    env_file:
      - .env.local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DEV}
      MYSQL_PORT_DEV: ${MYSQL_PORT_DEV}
    container_name: pepes-imprenta-grafica-db
    # ports:
    #   - ${MYSQL_PORT_DEV}
    stdin_open: true
    tty: true
