version: '3'

services:
  mysql:
    image: mysql:oraclelinux8
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_CONTAINER_DEV}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: ${MYSQL_CONTAINER_NAME_DEV}
    ports:
      - ${MYSQL_PORTS_CONTAINER_DEV}
    stdin_open: true
    tty: true
