@baseUrl= http://localhost:3000/api/ordenes/loma

###
POST {{baseUrl}}
Content-Type: application/json

{
  "id_cliente": ,
  "atendido_por": ,
  "fecha_entrega": ,
  "hora_entrega": ,
  "muestra": ,
  "ubicacion_archivo": ,
  "material": ,
  "orientacion": ,
  "bolsillo": ,
  "corte": ,
  "ojales": ,
  "troquelado": ,
  "portabaner": , 
  "observaciones": ,
  "total": ,
  "entrega": ,
  "estado": ,
  "metodo_pago": 
}

###
PATCH  {{baseUrl}}
Content-Type: application/json

{
  "fecha_entrega": ,
  "hora_entrega": ,
  "muestra": ,
  "ubicacion_archivo": ,
  "material": ,
  "orientacion": ,
  "bolsillo": ,
  "corte": ,
  "ojales": ,
  "troquelado": ,
  "portabaner": , 
  "observaciones": ,
  "total": ,
  "entrega": ,
  "estado": ,
  "metodo_pago": 
}