@baseUrl= http://localhost:3000/api/ordenes/volantes

###
POST {{baseUrl}}
Content-Type: application/json

{
  "id_cliente": 33,
  "atendido_por": "Vane",
  "fecha_entrega": "2024-03-03",
  "hora_entrega": "19:00",
  "muestra": "si",
  "tipo": "color",
  "tamano": "1/2",
  "cantidad": 250,
  "impresion": "frente",
  "ubicacion_diseno": "wasi",
  "observaciones": "",
  "total": 4689,
  "entrega": 3345,
  "estado": "pendiente",
  "metodo_pago": "efectivo"
}

###
PATCH  {{baseUrl}}
Content-Type: application/json

{
  "fecha_entrega": ,
  "hora_entrega": ,
  "muestra": ,
  "tipo": ,
  "tamano": ,
  "cantidad": ,
  "impresion": ,
  "ubicacion_diseno": ,
  "observaciones": ,
  "total": ,
  "entrega": ,
  "estado": ,
  "metodo_pago": 
}