@baseUrl= http://localhost:3000/api/empleados

### obtener todos los empleados
GET {{baseUrl}}

### crear un empleado
POST {{baseUrl}}
Content-Type: application/json

{
  "nickname": "Janamichi",
  "email": "janamichi@gmail.com",
  "password": "user123",
  "permisos": "user"
}

###
PATCH {{baseUrl}}/1
Content-Type: application/json

{
  "permisos": "admin"
}

###
DELETE {{baseUrl}}/3
