@baseUrl= http://localhost:3000/api/ordenes

###
GET {{baseUrl}}

###
POST {{baseUrl}}/loma
Content-Type: application/json

{
  "ubicacion_archivo": "compu 1",
  "estado": "pendiente"
}

###
GET {{baseUrl}}/loma/3

