name: Pepes imprenta y grafica

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        echo "
          AXIOS_BASE_URL=${{ secrets.AXIOS_BASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
        " >> .env.local
    - run: npm i
    - run: npm run build --if-present
    - run: pm2 reload pepes-imprenta-grafica